name: AutoGrade

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ "main" ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: temp
    if: github.actor != 'github-classroom[bot]'

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: CheckoutCode
        uses: actions/checkout@v4
      - name: DebugPrintouts
        run: |
          TIMESTAMP=`date +%Y-%m-%dT%H%M%SZ`
          echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
          echo "GITHUB_SHA=${GITHUB_SHA}"
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "GITHUB_WORKFLOW=${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTOR=${GITHUB_ACTOR}"
          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
          echo "SCRIPT_DIR=${SCRIPT_DIR}"
          echo "TIMESTAMP=${TIMESTAMP}"
          echo "GITHUB_TRIGGERING_ACTOR=${GITHUB_TRIGGERING_ACTOR}"
          WORKDIR=$(realpath "${GITHUB_WORKSPACE}/../..")
          echo "WORKDIR=${WORKDIR}"
      - name: Start autograding
        run: |
          WORKDIR=$(realpath "${GITHUB_WORKSPACE}/../..")
          FEEDBACK_FILE="${WORKDIR}/feedback.txt"
          TIMESTAMP=`date +%Y-%m-%dT%H%M%SZ`
          echo "" > ${FEEDBACK_FILE} # truncate the feedback file, this MUST be doe before creating the job.env file
          env | grep GITHUB > ${WORKDIR}/job.env
      - name: Autograding Reporter
        env:
          AG_COMPLETE: "Autograding complete" # TODO try to get fold this into the "notice" lines below
          AG_REPORT: "Autograding report"
          TIMEOUT: 10

        run: |
          WORKDIR=$(realpath "${GITHUB_WORKSPACE}/../..")
          FEEDBACK_FILE="${WORKDIR}/feedback.txt"
          echo "Waiting for the grader to finish ..."
          inotifywait -e close_write --timeout ${TIMEOUT} ${FEEDBACK_FILE}
          echo "Autograder finished"
          cat ${FEEDBACK_FILE}
          GRADER_POINTS=$(tail -n 1 ${FEEDBACK_FILE}) # The "notice" below transmits the grade to GitHub Classroom
          echo "::notice title=${AG_COMPLETE}::Points ${GRADER_POINTS}/100"
          echo "::notice title=${AG_REPORT}::{\"totalPoints\":${GRADER_POINTS},\"maxPoints\":100}"
